version: '3.9'

services:
  no_problems_bot:
    build:
      dockerfile: Dockerfile
      context: ..
    volumes:
      - /var/log/noproblemsbot:/app/logs
    depends_on:
      - redis


  redis:
    image: redis:7.2.3
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - /var/log/noproblemsbot:/data

volumes:
    redis_data:
