name: no_problems_bot

services:
  no_problems_bot:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    volumes:
      - /var/log/noproblemsbot:/app/logs
    depends_on:
      - redis


  redis:
    image: redis:7.2.3
    restart: on-failure
    volumes:
      - /var/log/noproblemsbot:/data

volumes:
    redis_data:

networks:
  npb:
    driver: bridge
